<?php
$modules = array (
  'auth' => 
  array (
    'name' => 'Авторизация',
    'nameb' => 'Войти',
    'acc' => 13,
    'opt' => 0,
    'perm' => 
    array (
    ),
    'pos' => 90,
  ),
  'cab' => 
  array (
    'name' => 'Личный кабинет',
    'nameb' => 'Личный<br>кабинет',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
    ),
    'pos' => 90,
  ),
  'default' => 
  array (
    'name' => 'Начало',
    'nameb' => 'Начало',
    'acc' => 63,
    'opt' => 1,
    'perm' => 
    array (
    ),
    'pos' => 50,
  ),
  'elec' => 
  array (
    'name' => 'Электричество',
    'nameb' => 'Электричество',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
  'expense' => 
  array (
    'name' => 'Расходы',
    'nameb' => 'Расходы',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
  'host' => 
  array (
    'name' => 'Хосты',
    'nameb' => 'Хосты',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор хостов',
    ),
    'pos' => 50,
  ),
  'income' => 
  array (
    'name' => 'Прибыль',
    'nameb' => 'Прибыль',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
  'lenta' => 
  array (
    'name' => 'Лента.ру',
    'nameb' => 'Лента.ру',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
    ),
    'pos' => 50,
  ),
  'log' => 
  array (
    'name' => 'Журнал',
    'nameb' => 'Журнал',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
    ),
    'pos' => 50,
  ),
  'people' => 
  array (
    'name' => 'Люди',
    'nameb' => 'Люди',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
  'user' => 
  array (
    'name' => 'Пользователи',
    'nameb' => 'Пользователи',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактирование профилей',
      'add' => 'добавление нового профиля',
      'edit_login' => 'редактирование логина и пароля',
      'edit_cat' => 'ред. кат. доступа',
    ),
    'pos' => 50,
  ),
  'visit' => 
  array (
    'name' => 'Визиты',
    'nameb' => 'Визиты',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
  'water' => 
  array (
    'name' => 'Вода',
    'nameb' => 'Вода',
    'acc' => 0,
    'opt' => 0,
    'perm' => 
    array (
      'edit' => 'редактор',
    ),
    'pos' => 50,
  ),
);
$submenu_icons = array (
  0 => 'br-amigo-12',
  1 => 'br-amigo-16',
  2 => 'br-amigo-9',
  3 => 'br-chrome-12',
  4 => 'br-chrome-16',
  5 => 'br-chrome-9',
  6 => 'br-chromium-12',
  7 => 'br-chromium-16',
  8 => 'br-chromium-9',
  9 => 'br-firefox-12',
  10 => 'br-firefox-16',
  11 => 'br-firefox-9',
  12 => 'br-iceweasel-12',
  13 => 'br-iceweasel-16',
  14 => 'br-iceweasel-9',
  15 => 'br-ie-12',
  16 => 'br-ie-16',
  17 => 'br-ie-9',
  18 => 'br-nichrom-12',
  19 => 'br-nichrom-16',
  20 => 'br-nichrom-9',
  21 => 'br-opera-12',
  22 => 'br-opera-16',
  23 => 'br-opera-9',
  24 => 'br-safari-12',
  25 => 'br-safari-16',
  26 => 'br-safari-9',
  27 => 'br-yandex-12',
  28 => 'br-yandex-16',
  29 => 'br-yandex-9',
  30 => 'calendar-select',
  31 => 'chain',
  32 => 'cross-button',
  33 => 'currency',
  34 => 'document--pencil',
  35 => 'document-list--plus',
  36 => 'document-list',
  37 => 'document-text--pencil',
  38 => 'document-text--plus',
  39 => 'document-text',
  40 => 'document',
  41 => 'funnel',
  42 => 'hammer-screwdriver',
  43 => 'holly',
  44 => 'image--plus',
  45 => 'image',
  46 => 'key',
  47 => 'lock',
  48 => 'magnifier',
  49 => 'medal',
  50 => 'minus-button',
  51 => 'na',
  52 => 'navigation-000-button',
  53 => 'navigation-090-button',
  54 => 'navigation-180-button',
  55 => 'navigation-270-button',
  56 => 'os-64',
  57 => 'os-ahrefs-12',
  58 => 'os-ahrefs-16',
  59 => 'os-ahrefs-9',
  60 => 'os-android-12',
  61 => 'os-android-16',
  62 => 'os-android-9',
  63 => 'os-android2-12',
  64 => 'os-android2-16',
  65 => 'os-android2-9',
  66 => 'os-android3-12',
  67 => 'os-android3-16',
  68 => 'os-android3-9',
  69 => 'os-android4-12',
  70 => 'os-android4-16',
  71 => 'os-android4-9',
  72 => 'os-android5-12',
  73 => 'os-android5-16',
  74 => 'os-android5-9',
  75 => 'os-bing-12',
  76 => 'os-bing-16',
  77 => 'os-bing-9',
  78 => 'os-google-12',
  79 => 'os-google-16',
  80 => 'os-google-9',
  81 => 'os-ipad-12',
  82 => 'os-ipad-16',
  83 => 'os-ipad-9',
  84 => 'os-iphone-12',
  85 => 'os-iphone-16',
  86 => 'os-iphone-9',
  87 => 'os-java-12',
  88 => 'os-java-16',
  89 => 'os-java-9',
  90 => 'os-linux-12',
  91 => 'os-linux-16',
  92 => 'os-linux-9',
  93 => 'os-mac-12',
  94 => 'os-mac-16',
  95 => 'os-mac-9',
  96 => 'os-sputnik-12',
  97 => 'os-sputnik-16',
  98 => 'os-sputnik-9',
  99 => 'os-ubuntu-12',
  100 => 'os-ubuntu-16',
  101 => 'os-ubuntu-9',
  102 => 'os-win10-12',
  103 => 'os-win10-16',
  104 => 'os-win10-9',
  105 => 'os-win7-12',
  106 => 'os-win7-16',
  107 => 'os-win7-9',
  108 => 'os-win8-12',
  109 => 'os-win8-16',
  110 => 'os-win8-9',
  111 => 'os-win81-12',
  112 => 'os-win81-16',
  113 => 'os-win81-9',
  114 => 'os-winserver-12',
  115 => 'os-winserver-16',
  116 => 'os-winserver-9',
  117 => 'os-winvista-12',
  118 => 'os-winvista-16',
  119 => 'os-winvista-9',
  120 => 'os-winxp-12',
  121 => 'os-winxp-16',
  122 => 'os-winxp-9',
  123 => 'os-yahoo-12',
  124 => 'os-yahoo-16',
  125 => 'os-yahoo-9',
  126 => 'os-yandex-12',
  127 => 'os-yandex-16',
  128 => 'os-yandex-9',
  129 => 'paper-clip',
  130 => 'pencil-button',
  131 => 'plus-button',
  132 => 'prohibition',
  133 => 'question-frame',
  134 => 'rainbow',
  135 => 'receipt-text--paper-clip',
  136 => 'receipt-text--plus',
  137 => 'receipt-text',
  138 => 'report--pencil',
  139 => 'table',
  140 => 'telephone--minus',
  141 => 'telephone--plus',
  142 => 'telephone-handset',
  143 => 'telephone',
  144 => 'tick-button',
  145 => 'user-green--chain',
  146 => 'user-green--list',
  147 => 'user-green--magnifier',
  148 => 'user-green--minus',
  149 => 'user-green--pencil',
  150 => 'user-green--plus',
  151 => 'wheel',
  152 => 'wrench-screwdriver',
);
?>