CREATE TABLE [auto] (id integer PRIMARY KEY AUTOINCREMENT,dt text,val integer,desc text);
CREATE TABLE [call] (id integer PRIMARY KEY AUTOINCREMENT,imei integer,pid integer,date text,time text,phone text,type integer,duration integer,name text);
CREATE TABLE [elec] (id integer PRIMARY KEY AUTOINCREMENT,dt text,val integer,desc text);
CREATE TABLE "expense" (id integer PRIMARY KEY AUTOINCREMENT,dt text,price integer,store integer,desc text);
CREATE TABLE "expense_doc" (id integer PRIMARY KEY AUTOINCREMENT,p integer,type integer);
CREATE TABLE "expense_item" (id integer PRIMARY KEY AUTOINCREMENT,p integer,price integer,quantity integer,type integer,desc text);
CREATE TABLE [host] (id integer PRIMARY KEY AUTOINCREMENT,ip integer,ipe integer,dateb text,datee text,metric integer,desc text,stat integer,color text,type integer);
CREATE TABLE [income] (id integer PRIMARY KEY AUTOINCREMENT,dt text,money integer,person integer,desc text);
CREATE TABLE [people] (id integer PRIMARY KEY AUTOINCREMENT,surname text,name text,otchestvo text,surnamef text,nickname text,birthdate text,deathdate text,vk text,ok text,fb text);
CREATE TABLE [people_addr] (id integer PRIMARY KEY AUTOINCREMENT,pid integer,addr text,lat integer,lon integer);
CREATE TABLE [people_group] (id integer PRIMARY KEY AUTOINCREMENT,people integer,group1 integer);
CREATE TABLE [people_junc] (id integer PRIMARY KEY AUTOINCREMENT,f integer,t integer,know integer,rel integer,symp integer,misc text);
CREATE TABLE [pgroup] (id integer PRIMARY KEY AUTOINCREMENT,desc text);
CREATE TABLE [phone] (id integer PRIMARY KEY AUTOINCREMENT,pid integer,num text,desc text);
CREATE TABLE [place] (id integer PRIMARY KEY AUTOINCREMENT,lat integer,lon integer,desc text);
CREATE TABLE [server] (id integer PRIMARY KEY AUTOINCREMENT,tp integer,desc text,logname text,rhost integer,format integer);
CREATE TABLE [sess] (id integer PRIMARY KEY AUTOINCREMENT,sid binary,stat integer,user integer,ip integer,ua text,date text,datel text);
CREATE TABLE [user] (id integer PRIMARY KEY AUTOINCREMENT,name text,cat integer,login text,pass binary);
CREATE TABLE [user_cat] (id integer PRIMARY KEY AUTOINCREMENT,desc text,perm text);
CREATE TABLE [visit] (id integer PRIMARY KEY AUTOINCREMENT,dt text,people integer,place integer,lat integer,lon integer,desc text);
CREATE TABLE [water] (id integer PRIMARY KEY AUTOINCREMENT,dt text,val integer,val2 integer,desc text);
